### ISSUE TITLE
Code review: resouces -> resources

### ISSUE THREAD

**Issue by larsw** [akhilputhiry/keycloak-client#19]
https://github.com/akhilputhiry/keycloak-client/blob/001a79dc6248417d8c9f5003c8bb7f2a2cb1c45c/keycloak/mixins/resource.py#L137

https://github.com/akhilputhiry/keycloak-client/blob/001a79dc6248417d8c9f5003c8bb7f2a2cb1c45c/keycloak/mixins/resource.py#L186

**Comment by akhilputhiry** [comment]
Thank you @larsw
