### ISSUE TITLE
Code review: should be possible to customize the list of requested scopes during authentication

### ISSUE THREAD

**Issue by larsw** [akhilputhiry/keycloak-client#22]
https://github.com/akhilputhiry/keycloak-client/blob/001a79dc6248417d8c9f5003c8bb7f2a2cb1c45c/keycloak/mixins/authentication.py#L32

**Comment by akhilputhiry** [comment]
Thank you @larsw for reviewing. Will fix it.

**Comment by larsw** [comment]
Be sure to verify that the only mandatory “openid” scope is in the list if the user can supply extra / custom scopes.
