### ISSUE TITLE
Code review: consider using the standard keycloak.json (Keycloak OIDC JSON) format

### ISSUE THREAD

**Issue by larsw** [akhilputhiry/keycloak-client#23]
Hi,

 It would be nice if ```keycloak-client``` could support the standard ```keycloak.json``` format that can be downloaded from the Keycloak Management Console (Realm -> Clients -> aClient -> Installation -> Format Option [Keycloak OIDC JSON]).

* The OIDC/UMA2 well-known discovery document URLs can be built from the values of ```auth-server-url``` and ```realm```.
* ```resource``` contains the ```client_id```.
* ```credentials/secret``` contains the ```client_secret```.
* ```verify-token-audience``` can be used to adjust the aud claim verification.

**Comment by akhilputhiry** [comment]
Sure @larsw I dont have time today. I have fixed other issued raised by you. Will fix this tomorrow or day after tomorrow.

**Comment by akhilputhiry** [comment]
This has been addressed by the [this](https://github.com/akhilputhiry/keycloak-client/commit/94e8815085558c03bf833d61c445c793d9a9b490) commit
