### ISSUE TITLE
Code review: None as default value for code is invalid.

### ISSUE THREAD

**Issue by larsw** [akhilputhiry/keycloak-client#24]
https://github.com/akhilputhiry/keycloak-client/blob/001a79dc6248417d8c9f5003c8bb7f2a2cb1c45c/keycloak/mixins/authentication.py#L37

Drop ```'=None'``` since it ends in a dead end/error.

**Comment by akhilputhiry** [comment]
That is explicitly handled

https://github.com/akhilputhiry/keycloak-client/blob/001a79dc6248417d8c9f5003c8bb7f2a2cb1c45c/keycloak/mixins/authentication.py#L51

**Comment by akhilputhiry** [comment]
Thank you @larsw
