### ISSUE TITLE
Code review: method to evict/refresh cached JWKs

### ISSUE THREAD

**Issue by larsw** [akhilputhiry/keycloak-client#25]
https://github.com/akhilputhiry/keycloak-client/blob/001a79dc6248417d8c9f5003c8bb7f2a2cb1c45c/keycloak/mixins/token.py#L19

Re. https://github.com/pydanny/cached-property#invalidating-the-cache

The JWK document should at least be refreshed once every 24h. The timer doesn't need to be implemented by this library, but it should expose a mechanism for evicting the cached property or refreshing the JWKs.

*Edit*: https://github.com/pydanny/cached-property#timing-out-the-cache might do the trick.

**Comment by akhilputhiry** [comment]
Thank you @larsw
